---
- name: Create config directory
  become: yes
  file:
    path: "{{platform_role.config.config_basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - platform

- name: Copy config.js
  become: yes
  notify: Restart o2r-platform
  template:
    src: "config.js.j2"
    dest: "{{platform_role.config.config_basepath}}/config.js"
    owner: root
    group: root
    mode: 0644
  tags:
    - platform

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-platform container
  template:
    src: o2r-platform.service.j2
    dest: "/etc/systemd/system/{{platform_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: platformcreate
  tags:
    - platform

- name: Pull image
  when: platformcreate.changed
  become: yes
  docker_image:
    name: "{{platform_role.container.image}}"
    state: present
    force: yes
  tags:
    - platform

- name: Enable service
  become: yes
  service:
    name: "{{platform_role.container.name}}"
    enabled: yes
  tags:
    - platform

- meta: flush_handlers
  tags:
    - platform

- name: Start service
  become: yes
  notify: Wait for o2r-platform to start up
  service:
    name: "{{platform_role.container.name}}"
    state: started
  tags:
    - platform

- meta: flush_handlers
  tags:
    - platform
