---
- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-bouncer container
  template:
    src: o2r-bouncer.service.j2
    dest: "/etc/systemd/system/{{bouncer_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  tags:
    - bouncer
    - microservice

- name: Enable service
  become: yes
  service:
    name: "{{bouncer_role.container.name}}"
    enabled: yes
  tags:
    - bouncer
    - microservice

- meta: flush_handlers
  tags:
    - bouncer
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-bouncer to start up
  service:
    name: "{{bouncer_role.container.name}}"
    state: started
  tags:
    - bouncer
    - microservice

- meta: flush_handlers
  tags:
    - bouncer
    - microservice
