---
- name: Create config directories
  become: yes
  file:
    path: /etc/o2r/supervisor
    state: directory
    mode: 0755

- name: Copy configuration file
  become: yes
  notify:
    - Restart o2r-supervisor
  template:
    src: endpoints.js.j2
    dest: /etc/o2r/supervisor/endpoints.js
    owner: root
    group: root
    mode: 0600

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-supervisor container
  template:
    src: o2r-supervisor.service.j2
    dest: /etc/systemd/system/o2r-supervisor.service
    owner: root
    group: root
    mode: 0600

#- name: Enable service
#  become: yes
#  service: name=o2r-supervisor enabled=yes

- meta: flush_handlers

#- name: Start service
#  become: yes
#  notify: Wait for o2r-supervisor to start up
#  service: name=o2r-supervisor state=started

- name: Stop service
  become: yes
  notify: Wait for o2r-supervisor to start up
  service: name=o2r-supervisor state=stopped

- meta: flush_handlers
