---
- name: Copy journald config file
  become: yes
  notify: restart journald
  copy:
    src: "journald.conf"
    dest: "/etc/systemd/journald.conf"
    owner: root
    group: root
    mode: 0600
  tags: production
