---
- name: Create data directory
  become: yes
  file:
    path: "{{transporter_role.config.basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - transporter
    - microservice

- name: Create service
  become: yes
  notify:
    - Reload Systemd
  template:
    src: o2r-transporter.service.j2
    dest: "/etc/systemd/system/{{transporter_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: transportercreate
  tags:
    - transporter
    - microservice

- name: Pull image
  when: transportercreate.changed
  become: yes
  docker_image:
    name: "{{transporter_role.container.image}}"
    state: present
    force: yes
  tags:
    - transporter
    - microservice

- name: Remove old o2r-transporter container
  become: yes
  notify: Wait for o2r-transporter
  docker_container:
    name: "{{transporter_role.container.name}}"
    state: absent
    force_kill: yes
  tags:
    - transporter
    - microservice

- name: Enable service
  become: yes
  service:
    name: "{{transporter_role.container.name}}"
    enabled: yes
  tags:
    - transporter
    - microservice

- meta: flush_handlers
  tags:
    - transporter
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-transporter
  service:
    name: "{{transporter_role.container.name}}"
    state: started
  tags:
    - transporter
    - microservice

- meta: flush_handlers
  tags:
    - transporter
    - microservice
