---
- name: Create data directory
  become: yes
  file:
    path: "{{transporter_role.config.basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-transporter container
  template:
    src: o2r-transporter.service.j2
    dest: "/etc/systemd/system/{{transporter_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600

- name: Enable service
  become: yes
  service:
    name: "{{transporter_role.container.name}}"
    enabled: yes

- meta: flush_handlers

- name: Start service
  become: yes
  notify: Wait for o2r-transporter to start up
  service:
    name: "{{transporter_role.container.name}}"
    state: started

- meta: flush_handlers
