---
- name: Create data directory
  become: yes
  file:
    path: "{{substituter_role.config.basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-substituter container
  template:
    src: o2r-substituter.service.j2
    dest: /etc/systemd/system/o2r-substituter.service
    owner: root
    group: root
    mode: 0600

- name: Enable service
  become: yes
  service: name=o2r-substituter enabled=yes

- meta: flush_handlers

- name: Start service
  become: yes
  notify: Wait for o2r-substituter to start up
  service: name=o2r-substituter state=started

- meta: flush_handlers
