---
transporter_role:
  config:
    basepath: "{{storage}}"
    port: 8081
    sessionsecret: "{{sessionsecret}}"
    mongo_host: "{{mongo_host}}"
    mongo_database: "{{mongo_database}}"
  container:
    image: "o2rproject/o2r-transporter:0.4.1"
    name: o2r-transporter
