---
- name: Install PIP
  become: yes
  yum: name=python-pip state=latest

- name: Upgrade PIP using PIP
  become: yes
  pip:
    name: pip
    extra_args: "--upgrade"

- name: Install "docker" from PIP
  become: yes
  pip:
    name: "{{item}}"
  with_items:
    - docker==3.3.0
  tags: docker-python
