---
- name: Install PIP
  become: yes
  yum: name=python-pip state=latest

- name: Upgrade PIP using PIP
  become: yes
  pip:
    name: pip
    extra_args: "--upgrade"

- name: Install docker-py from PIP
  become: yes
  pip:
    name: "{{item}}"
  with_items:
    - six==1.10
    - docker-py==1.10.6
