---
- name: Reload Systemd
  become: yes
  command: systemctl daemon-reload

- name: Restart o2r-transporter
  become: yes
  notify: Wait for o2r-transporter
  service:
    name: "{{transporter_role.container.name}}"
    state: restarted

- name: Wait for o2r-transporter
  pause: seconds=5
