---
- name: Create config directory
  become: yes
  file:
    path: "/etc/matomo-docker"
    state: directory
    mode: 0755
  tags: matomo

- name: Copy config.ini.php
  become: yes
  notify: restart matomo
  template:
    src: "config.ini.php.j2"
    dest: "/etc/matomo-docker/config.ini.php"
    owner: root
    group: root
    mode: 0644
  tags: matomo

- name: Remove old matomo container
  become: yes
  docker_container:
    name: matomo
    state: absent
  tags: matomo

- name: Start matomo container
  become: yes
  docker_container:
    name: matomo
    image: matomo:3.6
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{docker_mariadb_root_pass}}"
    links:
      - mariadb:db
    volumes:
      - /etc/matomo-docker/config.ini.php:/piwik/config/config.ini.php:rw
  notify: Wait for matomo to start up
  tags: matomo

- name: run command to increase number of custom variables
  become: yes
  shell: "docker exec -i piwik /piwik/console customvariables:set-max-custom-variables 10 --no-interaction"
  register: customvarout
  tags: matomo

- name: print result of custom variable config command
  debug:
    msg: "{{customvarout.stdout_lines}}"
  tags: matomo
