---
- name: Add MongoDB repo
  become: yes
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  tags: mongodb

- name: Configure SELinux to use "permissive" mode
  become: yes
  copy:
    src: selinux_config
    dest: /etc/selinux/config
    owner: root
    group: root
  tags: mongodb

- name: Install MongoDB server
  become: yes
  yum: name=mongodb-org-server state=latest
  notify: Restart MongoDB
  tags: mongodb

- name: Install MongoDB shell
  become: yes
  yum: name=mongodb-org-shell state=latest
  tags: mongodb

- name: Install MongoDB tools
  become: yes
  yum: name=mongodb-org-tools state=latest
  tags: mongodb

- name: Make sure MongoDB data directory exists
  become: yes
  file:
    path: "/data/db"
    state: directory
    owner: mongod
    group: mongod
    mode: 0755
  tags: mongodb

# Allow MongoDB to listen on tcp port 27017
# semanage port -a -t mongod_port_t -p tcp 27017 (from https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/)
# FIXME
#- name: Configure selinux
#  seport:
#    ports: "27017"
#    proto: "tcp"
#    setype: "mongod_port_t"
#    state: present
#  tags: mongodb

- name: Configure MongoDB
  become: yes
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MongoDB
  tags: mongodb

- name: Enable MongoDB Unit
  become: yes
  service: name=mongod state=started enabled=yes
  tags: mongodb

- meta: flush_handlers

- name: Initiate replica set
  shell: "mongo --eval 'printjson(rs.initiate())'"
  register: mongoinitout
  tags: mongodb

- name: print mongo cli result 1
  debug:
    msg: "{{mongoinitout.stdout_lines}}"
  tags: mongodb

- name: Status of replica set
  shell: "mongo --eval 'printjson(rs.status())'"
  register: mongostatusout
  tags: mongodb

- name: print mongo cli result 2
  debug:
    msg: "{{mongostatusout.stdout_lines}}"
  tags: mongodb

- meta: flush_handlers