---
- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-informer container
  template:
    src: o2r-informer.service.j2
    dest: /etc/systemd/system/o2r-informer.service
    owner: root
    group: root
    mode: 0600

- name: Enable service
  become: yes
  service:
    name: "{{informer_role.container.name}}"
    enabled: yes

- meta: flush_handlers

- name: Start service
  become: yes
  notify: Wait for o2r-informer to start up
  service:
    name: "{{informer_role.container.name}}"
    state: started

- meta: flush_handlers
