---
- hosts: master
  roles:
    # EPEL is needed for docker, etc.
    - epel
    - docker
    - docker-py
    - docker-mariadb
    #- docker-piwik
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.http_proxy}}"
