---
substituter_role:
  config:
    basepath: "/data/docker/o2r"
    port: 8090
    sessionsecret: "{{sessionsecret}}"
    mongo_host: "{{mongo_host}}"
    mongo_database: "{{mongo_database}}"
  container:
    image: "o2rproject/o2r-substituter:0.4.1"
    name: o2r-substituter
